<!-- 
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="120px"
    size="default" @submit.prevent>
    <div class="static-content-item">
    </div>
    <div class="tab-container">
      <el-tabs v-model="tab60554ActiveTab" type="border-card">
        <el-tab-pane name="tab1" label="值日">
          <el-form-item label="值日生姓名" prop="input12931" class="required label-right-align">
            <el-input v-model="formData.input12931" type="text" clearable></el-input>
          </el-form-item>
          <el-form-item label="选择当前日期" prop="date68627" class="required label-right-align">
            <el-date-picker v-model="formData.date68627" type="date" class="full-width-input"
              format="YYYY-MM-DD" value-format="YYYY-MM-DD" clearable></el-date-picker>
          </el-form-item>
          <el-form-item label="值日截图" prop="pictureupload46268" class="required label-right-align">
            <el-upload :file-list="pictureupload46268FileList" :headers="pictureupload46268UploadHeaders"
              :data="pictureupload46268UploadData" list-type="picture-card" multiple show-file-list
              :limit="3"> <template #default><i class="el-icon-plus"></i></template></el-upload>
          </el-form-item>
          <div class="static-content-item">
            <el-button type="primary">提交</el-button>
          </div>
        </el-tab-pane>
      </el-tabs>
    </div>
  </el-form>
  
</template>

<script>
  import {
    defineComponent,
    toRefs,
    reactive,
    getCurrentInstance
  }
  from 'vue'
  export default defineComponent({
    components: {},
    name: "zhiri",
    props: {},
    setup() {
      const state = reactive({
        formData: {
          input12931: "",
          date68627: null,
          pictureupload46268: null,
        },
        rules: {
          input12931: [{
            required: true,
            message: '字段值不可为空',
          }, {
            pattern: /^[一-龥]+$/,
            trigger: ['blur', 'change'],
            message: '请填写正确姓名'
          }],
          date68627: [{
            required: true,
            message: '字段值不可为空',
          }],
          pictureupload46268: [{
            required: true,
            message: '字段值不可为空',
          }],
        },
        'tab60554ActiveTab': 'tab1',
        pictureupload46268FileList: [],
        pictureupload46268UploadHeaders: {},
        pictureupload46268UploadData: {},
      })
      const instance = getCurrentInstance()
      const submitForm = () => {
        instance.proxy.$refs['vForm'].validate(valid => {
          if (!valid) return
          //TODO: 提交表单
        })
      }
      const resetForm = () => {
        instance.proxy.$refs['vForm'].resetFields()
      }
      return {
        ...toRefs(state),
        submitForm,
        resetForm
      }
    }
  })
  
</script>

<style lang="scss">
  .el-input-number.full-width-input,
  .el-cascader.full-width-input {
    width: 100% !important;
  }
  
  .el-form-item--medium {
    .el-radio {
      line-height: 36px !important;
    }
    
    .el-rate {
      margin-top: 8px;
    }
  }
  
  .el-form-item--small {
    .el-radio {
      line-height: 32px !important;
    }
    
    .el-rate {
      margin-top: 6px;
    }
  }
  
  .el-form-item--mini {
    .el-radio {
      line-height: 28px !important;
    }
    
    .el-rate {
      margin-top: 4px;
    }
  }
  
  .clear-fix:before,
  .clear-fix:after {
    display: table;
    content: "";
  }
  
  .clear-fix:after {
    clear: both;
  }
  
  .float-right {
    float: right;
  }
  
</style>

<style lang="scss" scoped>
  div.table-container {
    table.table-layout {
      width: 100%;
      table-layout: fixed;
      border-collapse: collapse;

      td.table-cell {
        display: table-cell;
        height: 36px;
        border: 1px solid #e1e2e3;
      }
    }
  }
  
div.tab-container {}
  
  .label-left-align :deep(.el-form-item__label) {
    text-align: left;
  }
  
  .label-center-align :deep(.el-form-item__label) {
    text-align: center;
  }
  
  .label-right-align :deep(.el-form-item__label) {
    text-align: right;
  }
  
.custom-label {}
  
  .static-content-item {
    min-height: 20px;
    display: flex;
    align-items: center;

    :deep(.el-divider--horizontal) {
      margin: 0;
    }
  }
  
</style>