<!-- 
Codes Generated By VForm:
https://www.vform666.com
-->

<!-- <template>
  <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="120px"
    size="default" @submit.prevent>
    <div class="static-content-item">
    </div>
    <div class="tab-container">
      <el-tabs v-model="tab60554ActiveTab" type="border-card">
        <el-tab-pane name="tab1" label="值日">
          <el-form-item label="值日生姓名" prop="input12931" class="required label-right-align">
            <el-input v-model="formData.input12931" type="text" clearable></el-input>
          </el-form-item>
          <el-form-item label="选择当前日期" prop="date68627" class="required label-right-align">
            <el-date-picker v-model="formData.date68627" type="date" class="full-width-input"
              format="YYYY-MM-DD" value-format="YYYY-MM-DD" clearable></el-date-picker>
          </el-form-item>
          <el-form-item label="值日截图" prop="pictureupload46268" class="required label-right-align">
            <el-upload :file-list="pictureupload46268FileList" :headers="pictureupload46268UploadHeaders"
              :data="pictureupload46268UploadData" list-type="picture-card" multiple show-file-list
              :limit="3"> <template #default><i class="el-icon-plus"></i></template></el-upload>
          </el-form-item>
          <div class="static-content-item">
            <el-button type="primary">提交</el-button>
          </div>
        </el-tab-pane>
      </el-tabs>
    </div>
  </el-form>
  
</template>

<script>
  import {
    defineComponent,
    toRefs,
    reactive,
    getCurrentInstance
  }
  from 'vue'
  export default defineComponent({
    components: {},
    name: "zhiri",
    props: {},
    setup() {
      const state = reactive({
        formData: {
          input12931: "",
          date68627: null,
          pictureupload46268: null,
        },
        rules: {
          input12931: [{
            required: true,
            message: '字段值不可为空',
          }, {
            pattern: /^[一-龥]+$/,
            trigger: ['blur', 'change'],
            message: '请填写正确姓名'
          }],
          date68627: [{
            required: true,
            message: '字段值不可为空',
          }],
          pictureupload46268: [{
            required: true,
            message: '字段值不可为空',
          }],
        },
        'tab60554ActiveTab': 'tab1',
        pictureupload46268FileList: [],
        pictureupload46268UploadHeaders: {},
        pictureupload46268UploadData: {},
      })
      const instance = getCurrentInstance()
      const submitForm = () => {
        instance.proxy.$refs['vForm'].validate(valid => {
          if (!valid) return
          //TODO: 提交表单
        })
      }
      const resetForm = () => {
        instance.proxy.$refs['vForm'].resetFields()
      }
      return {
        ...toRefs(state),
        submitForm,
        resetForm
      }
    }
  })
  
</script>

<style lang="scss">
  .el-input-number.full-width-input,
  .el-cascader.full-width-input {
    width: 80% !important;
    transition: all 0.3s ease; // 渐入渐出效果
  }
  
  .el-form-item--medium {
    .el-radio {
      line-height: 36px !important;
      transition: all 0.3s ease; // 渐入渐出效果
    }
    
    .el-rate {
      margin-top: 8px;
      transition: all 0.3s ease; // 渐入渐出效果
    }
  }
  
  .el-form-item--small {
    .el-radio {
      line-height: 32px !important;
      transition: all 0.3s ease; // 渐入渐出效果
    }
    
    .el-rate {
      margin-top: 6px;
      transition: all 0.3s ease; // 渐入渐出效果
    }
  }
  
  .el-form-item--mini {
    .el-radio {
      line-height: 28px !important;
      transition: all 0.3s ease; // 渐入渐出效果
    }
    
    .el-rate {
      margin-top: 4px;
      transition: all 0.3s ease; // 渐入渐出效果
    }
  }
  
  .clear-fix:before,
  .clear-fix:after {
    display: table;
    content: "";
  }
  
  .clear-fix:after {
    clear: both;
  }
  
  .float-right {
    float: right;
  }
  
  .blur-effect {
    backdrop-filter: blur(10px); // 毛玻璃效果
    border-radius: 10px; // 圆角效果
  }
  .el-button--primary{
    position: absolute;
    background-color: #050b7d;
    border-color: #096296;
    width: 20%;
    height: 40px;
    left:40%;
    right:40%;

  }
</style>

<style lang="scss" scoped>
  div.table-container {
    table.table-layout {
      width: 100%;
      table-layout: fixed;
      border-collapse: collapse;
      transition: all 0.3s ease; // 渐入渐出效果

      td.table-cell {
        display: table-cell;
        height: 36px;
        border: 1px solid #e1e2e3;
        backdrop-filter: blur(5px); // 毛玻璃效果
        border-radius: 5px; // 圆角效果
      }
    }
  }
  
  .label-left-align :deep(.el-form-item__label) {
    text-align: left;
  }
  
  .label-center-align :deep(.el-form-item__label) {
    text-align: center;
  }
  
  .label-right-align :deep(.el-form-item__label) {
    text-align: right;
  }
  
  .static-content-item {
    min-height: 20px;
    display: flex;
    align-items: center;
    transition: all 0.3s ease; // 渐入渐出效果
    backdrop-filter: blur(5px); // 毛玻璃效果
    border-radius: 5px; // 圆角效果

    :deep(.el-divider--horizontal) {
      margin: 0;
    }
  }
</style> -->

<!-- <script setup lang="ts">
import { ref } from 'vue'
import type { UploadFile } from 'element-plus'

const name = ref('')
const date = ref('')
const imageUrl = ref('')

const handleFileUpload = (file: UploadFile) => {
  const reader = new FileReader()
  reader.onload = (e) => {
    imageUrl.value = e.target?.result as string
  }
  reader.readAsDataURL(file.raw!)
}

const submitDutyRecord = () => {
  console.log('Duty record submitted:', { name: name.value, date: date.value, imageUrl: imageUrl.value })
  // Here you would typically send this data to a backend server
  alert('值日记录提交成功！')
}
</script>

<template>
  <div class="frosted-glass">
    <h2 class="header">值日记录</h2>
    <el-form @submit.prevent="submitDutyRecord" label-position="top">
      <el-form-item label="值日生姓名">
        <el-input v-model="name" placeholder="请输入姓名"></el-input>
      </el-form-item>
      <el-form-item label="值日日期">
        <el-date-picker v-model="date" type="date" placeholder="选择日期" style="width: 100%;"></el-date-picker>
      </el-form-item>
      <el-form-item label="值日截图">
        <el-upload
          class="upload-demo"
          drag
          action="#"
          :auto-upload="false"
          :on-change="handleFileUpload"
          accept="image/*"
        >
          <el-icon class="el-icon--upload"><upload-filled /></el-icon>
          <div class="el-upload__text">
            拖拽文件到此处或 <em>点击上传</em>
          </div>
        </el-upload>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" native-type="submit" style="width: 100%;">提交</el-button>
      </el-form-item>
    </el-form>
    <div v-if="imageUrl" class="preview">
      <h3>预览图片:</h3>
      <img :src="imageUrl" alt="Preview" style="max-width: 100%; max-height: 200px;" />
    </div>
  </div>
</template>

<style scoped>
.frosted-glass {
  width: 100%;
  max-width: 500px;
  margin: 0 auto;
  padding: 30px;
  box-sizing: border-box;
}
.header{
  text-align: center;
}


.el-form {
  text-align: left;
}

.el-form-item {
  margin-bottom: 20px;
}

.preview {
  margin-top: 30px;
  text-align: center;
}

.preview h3 {
  margin-bottom: 10px;
  color: #333;
}

:deep(.el-form-item__label) {
  font-weight: bold;
  color: #333;
}

:deep(.el-input__wrapper),
:deep(.el-date-editor.el-input__wrapper) {
  width: 100%;
}

:deep(.el-upload) {
  width: 100%;
}

:deep(.el-upload-dragger) {
  width: 100%;
}
</style> -->



<template>
  <div id="main" style="width: 600px;height:400px;"></div>
</template>

<script>
import * as echarts from 'echarts';

export default {
  name: 'WorkTimeChart',
  mounted() {
    this.drawChart();
  },
  methods: {
    drawChart() {
      var myChart = echarts.init(document.getElementById('main'));

      var option = {
        title: {
          text: '一周工作时间折线图'
        },
        tooltip: {
          trigger: 'axis'
        },
        legend: {
          data: ['工作时间']
        },
        grid: {
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        toolbox: {
          feature: {
            saveAsImage: {}
        }
        },
        xAxis: {
          type: 'category',
          boundaryGap: false,
          data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
        },
        yAxis: {
          type: 'value'
        },
        series: [
          {
            name: '工作时间',
            type: 'line',
            data: [8, 8, 8, 9, 8, 3, 2],
            markPoint: {
              data: [
                {type: 'max', name: '最大值'},
                {type: 'min', name: '最小值'}
              ]
            },
            markLine: {
              data: [
                {type: 'average', name: '平均值'}
              ]
            }
          }
        ]
      };

      myChart.setOption(option);
    }
  }
}
</script>

<style>
/* 你可以在这里添加 CSS 样式 */
</style>